---
title: "modelling practice in airfare"
format: html
---

```{r}
#| label: library-and-data-import
#| message: FALSE
#| warning: FALSE
#| echo: FALSE

library(readr)
library(dplyr)
library(ggplot2)
library(stringr)
library(tidyr)
library(tidymodels)

airfare <- read_csv("data/airfare-data-top-thousand-markets.csv")

airfare <- airfare %>% 
  mutate(fare = parse_number(fare),
         fare_lg = parse_number(fare_lg),
         fare_low = parse_number(fare_low))


```



```{r}
#| label: airfare-exploratory-analysis

# normalizing year and dropping unused columns
# filtering for post-2015 and only major U.S. carriers

airfare_post2015 <- airfare %>% 
  mutate(
    year_since_2015 = Year - 2015,
    covid = case_when(
      Year == 2020 | Year == 2021 ~ TRUE,
      TRUE ~ FALSE
    )
  ) %>% 
  select(
    -table_1_flag,
    -contains("Geocoded")
  ) %>% 
  filter(
    carrier_lg %in% c("B6", "WN", "DL", "UA", "AS", "AA", "NK", "F9"),
    year_since_2015 >= 0
  )

airfare_post2015$quarter <- as.factor(airfare_post2015$quarter)
airfare_post2015$carrier_lg <- as.factor(airfare_post2015$carrier_lg)
airfare_post2015$carrier_low <- as.factor(airfare_post2015$carrier_low)

large_carrier_airfare <- airfare_post2015 %>% 
  filter(carrier_lg %in% c("AA", "DL", "UA", "AK"))

large_carrier_airfare <- large_carrier_airfare |>
  mutate(carrier_lg = relevel(factor(carrier_lg), ref = "AA"))

fit <- lm(
  fare ~ carrier_lg +
         nsmiles +
         passengers +
         lf_ms +
         large_ms +
         year_since_2015 + quarter,
  data = large_carrier_airfare
)

summary(fit)
```

